airflow_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: dbt
      threads: 4
